blank_issues_enabled: false
contact_links:
  - name: ğŸ“¢ å®‰å…¨æ¼æ´æŠ¥å‘Š
    url: https://github.com/emlog/emlog/security/advisories
    about: å‘ç°å®‰å…¨é—®é¢˜ï¼Ÿè¯·æŒ‰ç…§æ­¤æŒ‡å—æäº¤ï¼Œä¸è¦å…¬å¼€å‘å¸ƒï¼