blank_issues_enabled: false
contact_links:
  - name: ğŸš¨ å®‰å…¨æ¼æ´æŠ¥å‘Š
    url: https://github.com/emlog/emlog/blob/master/SECURITY.md
    about: å‘ç°å®‰å…¨é—®é¢˜ï¼Ÿè¯·æŒ‰ç…§æ­¤æŒ‡å—æäº¤ï¼Œä¸è¦å…¬å¼€å‘å¸ƒåœ¨Issueä¸­ï¼